language: node_js
node_js:
  - "4.2"
sudo: false
install:
  - npm install
  - npm install eslint
script: npm run-script test
deploy:
  provider: script
  skip_cleanup: true
  script: publish.sh
  on:
    tags: true
    repo: otsimogames/core-memory-game
