language: node_js
node_js:
- 4.4.1
sudo: false
install: npm install
script: npm run-script buildandpublish
before_install:
- openssl aes-256-cbc -K $encrypted_63b41d8350f9_key -iv $encrypted_63b41d8350f9_iv
  -in .npmrc.enc -out ~\/.npmrc -d
